import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function seedGamificationQuests() {
  console.log("🎯 Görev verileri ekleniyor...");

  // Günlük Görevler
  const dailyQuests = [
    {
      id: "daily-login",
      type: "DAILY",
      category: "ACTIVITY",
      title: "Günlük Giriş",
      description: "Bugün platforma giriş yap",
      icon: "🌅",
      targetType: "LOGIN",
      targetValue: 1,
      coinReward: 10,
      xpReward: 5,
      isActive: true,
      priority: 1,
    },
    {
      id: "daily-create-plan",
      type: "DAILY",
      category: "PLAN",
      title: "Plan Oluştur",
      description: "Bugün bir plan oluştur",
      icon: "📝",
      targetType: "CREATE_PLAN",
      targetValue: 1,
      coinReward: 30,
      xpReward: 20,
      isActive: true,
      priority: 2,
    },
    {
      id: "daily-like-3",
      type: "DAILY",
      category: "SOCIAL",
      title: "3 Plan Beğen",
      description: "Bugün 3 plan beğen",
      icon: "❤️",
      targetType: "LIKE_COUNT",
      targetValue: 3,
      coinReward: 15,
      xpReward: 10,
      isActive: true,
      priority: 3,
    },
    {
      id: "daily-comment-2",
      type: "DAILY",
      category: "SOCIAL",
      title: "2 Yorum Yap",
      description: "Bugün 2 yorum yap",
      icon: "💬",
      targetType: "COMMENT_COUNT",
      targetValue: 2,
      coinReward: 20,
      xpReward: 15,
      isActive: true,
      priority: 4,
    },
    {
      id: "daily-view-5",
      type: "DAILY",
      category: "ACTIVITY",
      title: "5 Plan İncele",
      description: "Bugün 5 plan görüntüle",
      icon: "👀",
      targetType: "VIEW_COUNT",
      targetValue: 5,
      coinReward: 10,
      xpReward: 5,
      isActive: true,
      priority: 5,
    },
    {
      id: "daily-recipe-view",
      type: "DAILY",
      category: "RECIPE",
      title: "Tarif İncele",
      description: "Bugün 3 tarif görüntüle",
      icon: "🍽️",
      targetType: "RECIPE_VIEW_COUNT",
      targetValue: 3,
      coinReward: 10,
      xpReward: 5,
      isActive: true,
      priority: 6,
    },
    {
      id: "daily-confession-react",
      type: "DAILY",
      category: "SOCIAL",
      title: "İtiraf Reaksiyonu",
      description: "Bugün 3 itirafa reaksiyon ver",
      icon: "🎭",
      targetType: "CONFESSION_REACTION_COUNT",
      targetValue: 3,
      coinReward: 15,
      xpReward: 10,
      isActive: true,
      priority: 7,
    },
  ];

  // Haftalık Görevler
  const weeklyQuests = [
    {
      id: "weekly-create-3-plans",
      type: "WEEKLY",
      category: "PLAN",
      title: "3 Plan Oluştur",
      description: "Bu hafta 3 plan oluştur",
      icon: "📋",
      targetType: "CREATE_PLAN",
      targetValue: 3,
      coinReward: 100,
      xpReward: 75,
      isActive: true,
      priority: 1,
    },
    {
      id: "weekly-like-15",
      type: "WEEKLY",
      category: "SOCIAL",
      title: "15 Plan Beğen",
      description: "Bu hafta 15 plan beğen",
      icon: "💖",
      targetType: "LIKE_COUNT",
      targetValue: 15,
      coinReward: 75,
      xpReward: 50,
      isActive: true,
      priority: 2,
    },
    {
      id: "weekly-comment-10",
      type: "WEEKLY",
      category: "SOCIAL",
      title: "10 Yorum Yap",
      description: "Bu hafta 10 yorum yap",
      icon: "🗣️",
      targetType: "COMMENT_COUNT",
      targetValue: 10,
      coinReward: 80,
      xpReward: 60,
      isActive: true,
      priority: 3,
    },
    {
      id: "weekly-active-5-days",
      type: "WEEKLY",
      category: "ACTIVITY",
      title: "5 Gün Aktif Ol",
      description: "Bu hafta 5 gün giriş yap",
      icon: "📅",
      targetType: "ACTIVE_DAYS",
      targetValue: 5,
      coinReward: 120,
      xpReward: 100,
      isActive: true,
      priority: 4,
    },
    {
      id: "weekly-recipe-share",
      type: "WEEKLY",
      category: "RECIPE",
      title: "Tarif Paylaş",
      description: "Bu hafta 2 tarif paylaş",
      icon: "👨‍🍳",
      targetType: "CREATE_RECIPE",
      targetValue: 2,
      coinReward: 100,
      xpReward: 80,
      isActive: true,
      priority: 5,
    },
    {
      id: "weekly-confession-share",
      type: "WEEKLY",
      category: "SOCIAL",
      title: "İtiraf Paylaş",
      description: "Bu hafta 3 itiraf paylaş",
      icon: "🍰",
      targetType: "CREATE_CONFESSION",
      targetValue: 3,
      coinReward: 90,
      xpReward: 70,
      isActive: true,
      priority: 6,
    },
    {
      id: "weekly-play-games",
      type: "WEEKLY",
      category: "ACTIVITY",
      title: "Oyun Oyna",
      description: "Bu hafta 10 mini oyun oyna",
      icon: "🎮",
      targetType: "PLAY_GAME",
      targetValue: 10,
      coinReward: 50,
      xpReward: 40,
      isActive: true,
      priority: 7,
    },
  ];

  // Özel Görevler
  const specialQuests = [
    {
      id: "special-first-recipe",
      type: "SPECIAL",
      category: "RECIPE",
      title: "İlk Tarifini Paylaş",
      description: "İlk tarifini oluştur ve paylaş",
      icon: "🌟",
      targetType: "CREATE_RECIPE",
      targetValue: 1,
      coinReward: 50,
      xpReward: 30,
      isActive: true,
      priority: 1,
      conditions: {
        firstTime: true,
      },
    },
    {
      id: "special-10-plans",
      type: "SPECIAL",
      category: "PLAN",
      title: "10 Plan Ustası",
      description: "Toplam 10 plan oluştur",
      icon: "⭐",
      targetType: "TOTAL_PLANS",
      targetValue: 10,
      coinReward: 200,
      xpReward: 150,
      isActive: true,
      priority: 2,
    },
    {
      id: "special-50-likes",
      type: "SPECIAL",
      category: "SOCIAL",
      title: "Popüler Kullanıcı",
      description: "Planların toplam 50 beğeni alsın",
      icon: "🌟",
      targetType: "TOTAL_LIKES_RECEIVED",
      targetValue: 50,
      coinReward: 250,
      xpReward: 200,
      isActive: true,
      priority: 3,
    },
    {
      id: "special-100-comments",
      type: "SPECIAL",
      category: "SOCIAL",
      title: "Topluluk Lideri",
      description: "Toplam 100 yorum yap",
      icon: "👑",
      targetType: "TOTAL_COMMENTS",
      targetValue: 100,
      coinReward: 300,
      xpReward: 250,
      isActive: true,
      priority: 4,
    },
    {
      id: "special-level-10",
      type: "SPECIAL",
      category: "ACTIVITY",
      title: "Seviye 10'a Ulaş",
      description: "10. seviyeye ulaş",
      icon: "🏆",
      targetType: "REACH_LEVEL",
      targetValue: 10,
      coinReward: 500,
      xpReward: 0,
      isActive: true,
      priority: 5,
    },
    {
      id: "special-game-master",
      type: "SPECIAL",
      category: "ACTIVITY",
      title: "Oyun Ustası",
      description: "Her oyunda en az 1 kez yüksek skor yap",
      icon: "🎯",
      targetType: "GAME_HIGH_SCORES",
      targetValue: 3,
      coinReward: 400,
      xpReward: 300,
      isActive: true,
      priority: 6,
      conditions: {
        requireAllGames: true,
      },
    },
    {
      id: "special-social-butterfly",
      type: "SPECIAL",
      category: "SOCIAL",
      title: "Sosyal Kelebek",
      description: "Toplam 200 reaksiyon ver",
      icon: "🦋",
      targetType: "TOTAL_REACTIONS",
      targetValue: 200,
      coinReward: 350,
      xpReward: 280,
      isActive: true,
      priority: 7,
    },
    {
      id: "special-recipe-master",
      type: "SPECIAL",
      category: "RECIPE",
      title: "Tarif Ustası",
      description: "Toplam 25 tarif paylaş",
      icon: "👨‍🍳",
      targetType: "TOTAL_RECIPES",
      targetValue: 25,
      coinReward: 600,
      xpReward: 500,
      isActive: true,
      priority: 8,
    },
  ];

  const allQuests = [...dailyQuests, ...weeklyQuests, ...specialQuests];

  for (const quest of allQuests) {
    await prisma.quest.upsert({
      where: { id: quest.id },
      update: quest,
      create: quest,
    });
  }

  console.log(`✅ ${dailyQuests.length} günlük görev eklendi`);
  console.log(`✅ ${weeklyQuests.length} haftalık görev eklendi`);
  console.log(`✅ ${specialQuests.length} özel görev eklendi`);
  console.log(`🎯 Toplam ${allQuests.length} görev başarıyla eklendi!`);
}

seedGamificationQuests()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
