-- Add new badge types to BadgeType enum
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'QUEST_MASTER_10';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'QUEST_MASTER_50';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'QUEST_MASTER_100';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'COIN_COLLECTOR_1000';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'COIN_COLLECTOR_5000';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'COIN_COLLECTOR_10000';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'GAME_CALORIE_MASTER';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'GAME_MEMORY_MASTER';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'GAME_QUICK_CLICK_MASTER';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'SHOP_FIRST_PURCHASE';
ALTER TYPE "BadgeType" ADD VALUE IF NOT EXISTS 'SHOP_ENTHUSIAST_10';
